"""remove family_id from user

Revision ID: 3bc756afeafb
Revises: d6cee5c5e618
Create Date: 2025-03-23 20:39:36.708977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc756afeafb'
down_revision: Union[str, None] = 'd6cee5c5e618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_family_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'family_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_family_id_fkey', 'users', 'families', ['family_id'], ['id'])
    # ### end Alembic commands ###
